name: release
on:
  push:
    branches:
      - "*"
  workflow_dispatch:
    branches:
      - master
    inputs:
      type:
        type: choice
        description: "Release type"
        options:
          - major
          - minor
          - patch
defaults:
  run:
    shell: bash
env:
  GONOPROXY: github.com/afreyermuth98/*
  GONOSUMDB: github.com/afreyermuth98/*
  GOPRIVATE: github.com/afreyermuth98/*
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    - name: Go Test
      run: go test -v ./...
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: 
      - test
      - lint
    outputs:
      changewatch-exporter-arm64-darwin_sha256: ${{ steps.output-sha256sum.outputs.changewatch-exporter-arm64-darwin_sha256 }}
      changewatch-exporter-amd64-linux_sha256: ${{ steps.output-sha256sum.outputs.changewatch-exporter-amd64-linux_sha256 }}
      changewatch-exporter-arm64-linux_sha256: ${{ steps.output-sha256sum.outputs.changewatch-exporter-arm64-linux_sha256 }}
      changewatch-exporter-amd64-windows_sha256: ${{ steps.output-sha256sum.outputs.changewatch-exporter-amd64-windows_sha256 }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-changewatch-exporter-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        restore-keys: |
          ${{ runner.os }}-changewatch-exporter-
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    - name: Configure git
      run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - name: Build
      run: |
        mkdir -p ./bin
        go get
        go generate
        GOOS=darwin CGO_ENABLED=0 GOARCH=arm64 go build -o ./bin/changewatch-exporter-arm64-darwin main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o ./bin/changewatch-exporter-amd64-linux main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=arm64 go build -o ./bin/changewatch-exporter-arm64-linux main.go
        GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -o ./bin/changewatch-exporter-amd64-windows.exe main.go
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: changewatch-exporter
        path: ./bin
    - name: Export sha256sum
      id: output-sha256sum
      run: |
        echo "changewatch-exporter-arm64-darwin_sha256=$(sha256sum ./bin/changewatch-exporter-arm64-darwin | cut -f1 -d' ')" >> "$GITHUB_OUTPUT"
        echo "changewatch-exporter-amd64-linux_sha256=$(sha256sum ./bin/changewatch-exporter-amd64-linux | cut -f1 -d' ')" >> "$GITHUB_OUTPUT"
        echo "changewatch-exporter-arm64-linux_sha256=$(sha256sum ./bin/changewatch-exporter-arm64-linux | cut -f1 -d' ')" >> "$GITHUB_OUTPUT"
        echo "changewatch-exporter-amd64-windows_sha256=$(sha256sum ./bin/changewatch-exporter-amd64-windows.exe | cut -f1 -d' ')" >> "$GITHUB_OUTPUT"
  container:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      container_sha256: ${{ steps.build_and_push.outputs.digest }}
    needs: 
     - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}          
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: production
          platforms: linux/amd64,linux/arm64
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: 
     - container
     - build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get next tag version
      id: get_tag
      run: |
       ACTUAL_VERSION=$(git describe --tags --abbrev=0)
       if [[ ${{ github.event.inputs.type }} == "patch" ]]
       then
          echo "patch release ..."
          PATCH=$(echo $ACTUAL_VERSION | cut -d. -f3)
          MAJOR_AND_MINOR=$(echo $ACTUAL_VERSION | cut -d. -f1,2)
          VERSION_TO_RELEASE=$(printf "%s.%d" $MAJOR_AND_MINOR $(($PATCH + 1)))
        elif [[ ${{ github.event.inputs.type }} == "minor" ]]
        then
          echo "minor release ..."
          MAJOR=$(echo $ACTUAL_VERSION | cut -d. -f1)
          MINOR=$(echo $ACTUAL_VERSION | cut -d. -f2)
          VERSION_TO_RELEASE=$(printf "%d.%d.0" $MAJOR $(($MINOR + 1))) ;
        elif [[ ${{ github.event.inputs.type }} == "major" ]]
        then
          echo "major release ..."
          MAJOR=$(echo $ACTUAL_VERSION | cut -d. -f1)
          VERSION_TO_RELEASE=$(printf "%d.0.0" $(($MAJOR + 1))) ;
        else
            exit 1
        fi
        echo "tag=$VERSION_TO_RELEASE" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install gitmoji
      run: |
        npm install -g gitmoji-changelog
    - name: Generate changelog & tagging
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        VERSION_TO_RELEASE=${{ steps.get_tag.outputs.tag }}
        GITMOJI=$(jq '.project.version = $newTag' --arg newTag "${VERSION_TO_RELEASE//v}" .gitmoji-changelogrc)
        echo $GITMOJI > .gitmoji-changelogrc
        gitmoji-changelog --preset generic
        git add .gitmoji-changelogrc CHANGELOG.md
        git commit --no-verify -m ":bookmark: bumped to version $VERSION_TO_RELEASE"
        git tag -a "${VERSION_TO_RELEASE}" -m "${VERSION_TO_RELEASE}"
        git push origin HEAD:master --follow-tags
    - name: Retrieve the build artifacts
      uses: actions/download-artifact@v2
      with:
        name: changewatch-exporter
        path: ./bin
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: | 
          | Artifacts | SHA256SUM |
          | --- | --- |
          | changewatch-exporter-arm64-darwin | `${{ needs.build.outputs.changewatch-exporter-arm64-darwin_sha256 }}` |
          | changewatch-exporter-amd64-linux | `${{ needs.build.outputs.changewatch-exporter-amd64-linux_sha256 }}` |
          | changewatch-exporter-arm64-linux | `${{ needs.build.outputs.changewatch-exporter-arm64-linux_sha256 }}` |
          | changewatch-exporter-amd64-windows.exe | `${{ needs.build.outputs.changewatch-exporter-amd64-windows_sha256 }}` |
          | ghcr.io/afreyermuth98/changewatch-exporter:v${{ steps.get_tag.outputs.tag }} | `${{ needs.container.outputs.container_sha256 }}` |
        files: |
         ./bin/changewatch-exporter-arm64-darwin
         ./bin/changewatch-exporter-amd64-linux
         ./bin/changewatch-exporter-arm64-linux
         ./bin/changewatch-exporter-amd64-windows.exe
