name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Get tag version
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Retrieve the build artifacts
      uses: actions/download-artifact@v2
      with:
        name: changewatch-exporter
        path: ./bin
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        body: | 
          | Artifacts | SHA256SUM |
          | --- | --- |
          | changewatch-exporter-arm64-darwin | `${{ needs.build.outputs.changewatch-exporter-arm64-darwin_sha256 }}` |
          | changewatch-exporter-amd64-linux | `${{ needs.build.outputs.changewatch-exporter-amd64-linux_sha256 }}` |
          | changewatch-exporter-arm64-linux | `${{ needs.build.outputs.changewatch-exporter-arm64-linux_sha256 }}` |
          | changewatch-exporter-amd64-windows.exe | `${{ needs.build.outputs.changewatch-exporter-amd64-windows_sha256 }}` |
          | ghcr.io/afreyermuth98/changewatch-exporter:${{ steps.get_tag.outputs.tag }} | `${{ needs.container.outputs.container_sha256 }}` |
        files: |
         ./bin/changewatch-exporter-arm64-darwin
         ./bin/changewatch-exporter-amd64-linux
         ./bin/changewatch-exporter-arm64-linux
         ./bin/changewatch-exporter-amd64-windows.exe
